src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $category_name;

    #[ORM\OneToMany(mappedBy: 'product_category', targetEntity: Product::class)]
    private $category_products;

    #[ORM\Column(type: 'datetime_immutable')]
    private $category_created_at;

    public function __construct()
    {
        $this->category_products = new ArrayCollection();
        $this->category_created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getCategoryProducts(): Collection
    {
        return $this->category_products;
    }

    public function addCategoryProduct(Product $categoryProduct): self
    {
        if (!$this->category_products->contains($categoryProduct)) {
            $this->category_products[] = $categoryProduct;
            $categoryProduct->setProductCategory($this);
        }

        return $this;
    }

    public function removeCategoryProduct(Product $categoryProduct): self
    {
        if ($this->category_products->removeElement($categoryProduct)) {
            // set the owning side to null (unless already changed)
            if ($categoryProduct->getProductCategory() === $this) {
                $categoryProduct->setProductCategory(null);
            }
        }

        return $this;
    }

    public function getCategoryCreatedAt(): ?\DateTimeImmutable
    {
        return $this->category_created_at;
    }

    public function setCategoryCreatedAt(\DateTimeImmutable $category_created_at): self
    {
        $this->category_created_at = $category_created_at;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $product_title;

    #[ORM\Column(type: 'integer')]
    private $product_price;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $product_description;

    #[ORM\Column(type: 'datetime_immutable')]
    private $product_created_at;

    #[ORM\ManyToOne(targetEntity: Shop::class, inversedBy: 'shop_products')]
    private $product_shop;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'category_products')]
    #[ORM\JoinColumn(nullable: false)]
    private $product_category;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private $product_author;

    #[ORM\Column(type: 'string', length: 255)]
    private $product_images;

    public function __construct()
    {
        $this->product_created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductTitle(): ?string
    {
        return $this->product_title;
    }

    public function setProductTitle(string $product_title): self
    {
        $this->product_title = $product_title;

        return $this;
    }

    public function getProductPrice(): ?int
    {
        return $this->product_price;
    }

    public function setProductPrice(int $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->product_description;
    }

    public function setProductDescription(?string $product_description): self
    {
        $this->product_description = $product_description;

        return $this;
    }

    public function getProductCreatedAt(): ?\DateTimeImmutable
    {
        return $this->product_created_at;
    }

    public function setProductCreatedAt(\DateTimeImmutable $product_created_at): self
    {
        $this->product_created_at = $product_created_at;

        return $this;
    }

    public function getProductShop(): ?Shop
    {
        return $this->product_shop;
    }

    public function setProductShop(?Shop $product_shop): self
    {
        $this->product_shop = $product_shop;

        return $this;
    }

    public function getProductCategory(): ?Category
    {
        return $this->product_category;
    }

    public function setProductCategory(?Category $product_category): self
    {
        $this->product_category = $product_category;

        return $this;
    }

    public function getProductAuthor(): ?User
    {
        return $this->product_author;
    }

    public function setProductAuthor(?User $product_author): self
    {
        $this->product_author = $product_author;

        return $this;
    }

    public function getProductImages(): ?string
    {
        return $this->product_images;
    }

    public function setProductImages(string $product_images): self
    {
        $this->product_images = $product_images;

        return $this;
    }

    public function getImagePath(): string
    {
        return 'uploads/product_image/'.$this->getProductImages();
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('product_title', TextType::class, [
                'label' => 'Titre du produit',
                'attr' => [
                    'class' => 'input-custom mt-2',
                    'placeholder' => 'Titre'
                ],
            ])
            ->add('product_price', TextType::class, [
                'label' => 'Prix de produit',
                'attr' => [
                    'class' => 'input-custom mt-2',
                    'placeholder' => 'Prix'
                ],
            ])
            ->add('product_description', TextareaType::class, [
                'label' => 'Description du produit',
                'attr' => [
                    'class' => 'input-custom mt-2',
                    'placeholder' => 'Description'
                ],
            ])
            ->add('product_images', FileType::class, [
                'label' => 'Image du produit',
                'mapped' => false,
                'attr' => [
                    'class' => 'input-custom mt-2',
                ],
            ])
            ->add('product_category', EntityType::class, [
                    'label' => 'Catégorie du produit',
                    'class' => Category::class,
                    'choice_label' => 'category_name',
                    'attr' => [
                        'class' => 'input-custom mt-2',
                    ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\User;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    #[Route('/catalog', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('catalog/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    #[Route('/product/{id}', name: 'app_product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/product.html.twig', [
            'product' => $product,
        ]);
    }
}

templates/product/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CatalogController!{% endblock %}

{% block body %}
    <div class="product">
        <div class="list_images_product">
                <div class="container">
                    <div class="carousel">
                        <input type="radio" name="slides" checked="checked" id="slide-1">
                        <!-- <input type="radio" name="slides" id="slide-2"> -->
                        <ul class="carousel__slides">
                            <li class="carousel__slide">
                                <figure>
                                    <div>
                                        <!-- width="60%" -->
                                        <img class="image_product_carousel" src="{{ asset(product.imagePath) }}" alt="">
                                    </div>
                                </figure>
                            </li>
                        </ul>
                        <ul class="carousel__thumbnails">
                            <li>
                                <label for="slide-1"><img src="{{ asset(product.imagePath) }}" alt=""></label>
                            </li>
                        </ul>
                    </div>
                </div>
        </div>
        <div class="product_information">
            <div class="card_product-information">
                <h2>{{ product.productTitle }}</h2>
                <p class="product_category">{{ product.productCategory.categoryName }}</p>
                <hr>
                <button class="buy_button">Commander</button>
                <div class="accordion_container">
                    <button class="accordion">Description</button>
                    <div class="panel">
                        <p>{{ product.productDescription }}</p>
                    </div>
                </div>
                <table class="table_feature">
                    <tbody>
                    <tr>
                        <td class="feature_title">Date de mise en vente</td>
                        <td>12 Février 2022</td>
                    </tr>
                    <tr>
                        <td class="feature_title">Marque</td>
                        <td>Nike</td>
                    </tr>
                    <tr>
                        <td class="feature_title">Taille</td>
                        <td>XS</td>
                    </tr>
                    <tr>
                        <td class="feature_title">État</td>
                        <td>Neuf avec étiquette</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}