src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopRepository::class)]
class Shop
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $shop_name;

    #[ORM\Column(type: 'datetime_immutable')]
    private $shop_created_at;

    #[ORM\OneToOne(inversedBy: 'shop', targetEntity: User::class, cascade: ['persist', 'remove'])]
    private $shop_owner;

    #[ORM\OneToMany(mappedBy: 'product_shop', targetEntity: Product::class)]
    private $shop_products;

    public function __construct()
    {
        $this->shop_created_at = new \DateTimeImmutable();
        $this->shop_products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getShopName(): ?string
    {
        return $this->shop_name;
    }

    public function setShopName(string $shop_name): self
    {
        $this->shop_name = $shop_name;

        return $this;
    }

    public function getShopCreatedAt(): ?\DateTimeImmutable
    {
        return $this->shop_created_at;
    }

    public function setShopCreatedAt(\DateTimeImmutable $shop_created_at): self
    {
        $this->shop_created_at = $shop_created_at;

        return $this;
    }

    public function getShopOwner(): ?User
    {
        return $this->shop_owner;
    }

    public function setShopOwner(?User $shop_owner): self
    {
        $this->shop_owner = $shop_owner;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getShopProducts(): Collection
    {
        return $this->shop_products;
    }

    public function addShopProduct(Product $shopProduct): self
    {
        if (!$this->shop_products->contains($shopProduct)) {
            $this->shop_products[] = $shopProduct;
            $shopProduct->setProductShop($this);
        }

        return $this;
    }

    public function removeShopProduct(Product $shopProduct): self
    {
        if ($this->shop_products->removeElement($shopProduct)) {
            // set the owning side to null (unless already changed)
            if ($shopProduct->getProductShop() === $this) {
                $shopProduct->setProductShop(null);
            }
        }

        return $this;
    }
}

src/Form/ShopType.php
<?php

namespace App\Form;

use App\Entity\Shop;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShopType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('shop_name', TextType::class, [
                'attr' => [
                    'class' => 'input-custom',
                    'placeholder' => 'Nom de la boutique'
                    ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Shop::class,
        ]);
    }
}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Entity\Shop;
use App\Entity\User;
use App\Form\ShopType;
use App\Repository\ShopRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/shop')]
class ShopController extends AbstractController
{
    #[Route('/', name: 'app_shop_index', methods: ['GET'])]
    public function index(ShopRepository $shopRepository): Response
    {
        return $this->render('shop/index.html.twig', [
            'shops' => $shopRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_shop_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ShopRepository $shopRepository): Response
    {
        /** @var $user User */
        $user = $this->getUser();

        $shop = new Shop();
        $form = $this->createForm(ShopType::class, $shop);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $shop->setShopOwner($user);

            $this->addFlash(
                'success',
                'Ta boutique a bien été créée'
            );

            $shopRepository->add($shop);
            return $this->redirectToRoute('app_account', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('shop/new.html.twig', [
            'shop' => $shop,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_shop_show', methods: ['GET'])]
    public function show(Shop $shop): Response
    {
        return $this->render('shop/product.html.twig', [
            'shop' => $shop,
        ]);
    }
}

templates/shop/_form_edit.html.twig
{{ form_start(form, {'attr': {'class': 'w-100'}}) }}
    {{ form_label(form.shop_name, 'Nom de votre boutique') }}
    <div class="mt-2">
        {{ form_errors(form.shop_name) }}
        {{ form_widget(form.shop_name) }}
    </div>
<button class="action-button">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/shop/_form_new.html.twig
{{ form_start(form, {'attr': {'class': 'w-100 d-flex flex-column justify-content-center align-items-center py-4'}}) }}
    <div class="w-50 mb-4 d-flex flex-column justify-content-center align-items-center">
        {{ form_errors(form.shop_name) }}
        {{ form_widget(form.shop_name) }}
    </div>
    <button class="form-button">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/shop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Shop index{% endblock %}

{% block body %}
    <h1>Shop index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Shop_name</th>
                <th>Shop_created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for shop in shops %}
            <tr>
                <td>{{ shop.id }}</td>
                <td>{{ shop.shopName }}</td>
                <td>{{ shop.shopCreatedAt ? shop.shopCreatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_shop_show', {'id': shop.id}) }}">show</a>
                    <a href="{{ path('app_shop_edit', {'id': shop.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_shop_new') }}">Create new</a>
{% endblock %}

templates/shop/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Shop{% endblock %}

{% block body %}
    <div class="new-shop">
        <div class="new-shop-header">
            <h2 class="header-title">nouvelle boutique</h2>
        </div>
        <div class="w-100 d-flex flex-row justify-content-center py-5">
            <div class="form-new-shop w-50 d-flex flex-column justify-content-center align-items-center">
                <h3 class="form-title">Crée ta boutique personnalisable</h3>
                {{ include('shop/_form_new.html.twig') }}
                <a class="form-button text-white" href="{{ path('app_account') }}">Annuler</a>
            </div>
            <div class="draw-shop w-50 d-flex justify-content-center align-items-center">
                <img src="{{ asset("build/images/image_new_shop.jpeg") }}" alt="" width="80%">
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Shop{% endblock %}

{% block body %}
    <h1>Shop</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ shop.id }}</td>
            </tr>
            <tr>
                <th>Shop_name</th>
                <td>{{ shop.shopName }}</td>
            </tr>
            <tr>
                <th>Shop_created_at</th>
                <td>{{ shop.shopCreatedAt ? shop.shopCreatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_shop_index') }}">back to list</a>

    <a href="{{ path('app_shop_edit', {'id': shop.id}) }}">edit</a>

    {{ include('shop/_delete_form.html.twig') }}
{% endblock %}