src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $product_title;

    #[ORM\Column(type: 'integer')]
    private $product_price;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $product_description;

    #[ORM\Column(type: 'datetime_immutable')]
    private $product_created_at;

    #[ORM\ManyToOne(targetEntity: Shop::class, inversedBy: 'shop_products')]
    private $product_shop;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'category_products')]
    #[ORM\JoinColumn(nullable: false)]
    private $product_category;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private $product_author;

    #[ORM\Column(type: 'string', length: 255)]
    private $product_images;

    public function __construct()
    {
        $this->product_created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductTitle(): ?string
    {
        return $this->product_title;
    }

    public function setProductTitle(string $product_title): self
    {
        $this->product_title = $product_title;

        return $this;
    }

    public function getProductPrice(): ?int
    {
        return $this->product_price;
    }

    public function setProductPrice(int $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->product_description;
    }

    public function setProductDescription(?string $product_description): self
    {
        $this->product_description = $product_description;

        return $this;
    }

    public function getProductCreatedAt(): ?\DateTimeImmutable
    {
        return $this->product_created_at;
    }

    public function setProductCreatedAt(\DateTimeImmutable $product_created_at): self
    {
        $this->product_created_at = $product_created_at;

        return $this;
    }

    public function getProductShop(): ?Shop
    {
        return $this->product_shop;
    }

    public function setProductShop(?Shop $product_shop): self
    {
        $this->product_shop = $product_shop;

        return $this;
    }

    public function getProductCategory(): ?Category
    {
        return $this->product_category;
    }

    public function setProductCategory(?Category $product_category): self
    {
        $this->product_category = $product_category;

        return $this;
    }

    public function getProductAuthor(): ?User
    {
        return $this->product_author;
    }

    public function setProductAuthor(?User $product_author): self
    {
        $this->product_author = $product_author;

        return $this;
    }

    public function getProductImages(): ?string
    {
        return $this->product_images;
    }

    public function setProductImages(string $product_images): self
    {
        $this->product_images = $product_images;

        return $this;
    }

    public function getImagePath(): string
    {
        return 'uploads/product_image/'.$this->getProductImages();
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('product_title', TextType::class, [
                'label' => 'Titre du produit',
                'attr' => [
                    'class' => 'input-custom mt-2',
                    'placeholder' => 'Titre'
                ],
            ])
            ->add('product_price', TextType::class, [
                'label' => 'Prix de produit',
                'attr' => [
                    'class' => 'input-custom mt-2',
                    'placeholder' => 'Prix'
                ],
            ])
            ->add('product_description', TextareaType::class, [
                'label' => 'Description du produit',
                'attr' => [
                    'class' => 'input-custom mt-2',
                    'placeholder' => 'Description'
                ],
            ])
            ->add('product_images', FileType::class, [
                'label' => 'Image du produit',
                'mapped' => false,
                'attr' => [
                    'class' => 'input-custom mt-2',
                ],
            ])
            ->add('product_category', EntityType::class, [
                    'label' => 'Catégorie du produit',
                    'class' => Category::class,
                    'choice_label' => 'category_name',
                    'attr' => [
                        'class' => 'input-custom mt-2',
                    ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\User;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    #[Route('/catalog', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('catalog/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    #[Route('/product/{id}', name: 'app_product_show', methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/product.html.twig', [
            'product' => $product,
        ]);
    }
}

src/Controller/UserDashboardController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Shop;
use App\Entity\User;
use App\Form\ProductType;
use App\Form\ShopType;
use App\Repository\ProductRepository;
use App\Repository\ShopRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/shop-dashboard', name: 'app_user_dashboard_')]
class UserDashboardController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ShopRepository $shopRepository): Response
    {
        return $this->render('user_dashboard/index.html.twig', [
            'controller_name' => 'UserDashboardController',
        ]);
    }

    // ------------------------------
    // ----- PRODUCT MANAGEMENT -----
    // ------------------------------

    #[Route('/products', name: 'product_index', methods: ['GET'])]
    public function productIndex(ProductRepository $productRepository): Response
    {
        return $this->render('user_dashboard/product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    #[Route('/product/new', name: 'product_new', methods: ['GET', 'POST'])]
    public function productNew(Request $request, ProductRepository $productRepository): Response
    {
        /** @var $user User */
        $user = $this->getUser();

        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['product_images']->getData();
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/uploads/product_image';

                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $uploadedFile->guessExtension();

                $uploadedFile->move(
                    $destination,
                    $newFilename
                );
                $product->setProductImages($newFilename);
            }

            $product->setProductAuthor($user);
            $product->setProductShop($user->getShop());
            $productRepository->add($product);
            return $this->redirectToRoute('app_user_dashboard', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user_dashboard/product/new.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/product/{id}/edit', name: 'product_edit', methods: ['GET', 'POST'])]
    public function productEdit(Request $request, Product $product, ProductRepository $productRepository): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productRepository->add($product);
            return $this->redirectToRoute('app_user_dashboard', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user_dashboard/product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/product/{id}', name: 'product_delete', methods: ['POST'])]
    public function productDelete(Request $request, Product $product, ProductRepository $productRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $productRepository->remove($product);
        }

        return $this->redirectToRoute('app_user_dashboard', [], Response::HTTP_SEE_OTHER);
    }

    // ---------------------------
    // ----- SHOP MANAGEMENT -----
    // ---------------------------

    #[Route('/{id}/edit', name: 'shop_edit', methods: ['GET', 'POST'])]
    public function ShopEdit(Request $request, Shop $shop, ShopRepository $shopRepository): Response
    {
        $form = $this->createForm(ShopType::class, $shop);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $shopRepository->add($shop);
            return $this->redirectToRoute('app_shop_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user_dashboard/shop/edit.html.twig', [
            'shop' => $shop,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'shop_delete', methods: ['POST'])]
    public function shopDelete(Request $request, Shop $shop, ShopRepository $shopRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$shop->getId(), $request->request->get('_token'))) {
            $shopRepository->remove($shop);
        }

        return $this->redirectToRoute('app_shop_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user_dashboard/product/_delete_form.html.twig
<form class="mt-2" method="post" action="{{ path('app_user_dashboard_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Êtes-vous bien certains de vouloir supprimer ce produit ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="delete-button">Supprimer</button>
</form>

templates/user_dashboard/product/_form.html.twig
{{ form_start(form, {'attr': {'class': 'w-100'}}) }}
    {{ form_widget(form) }}
    <button class="action-button">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/user_dashboard/product/edit.html.twig
{% extends 'user_dashboard/index.html.twig' %}

{% block content %}
    <div class="container-bloc-dashboard w-50">
        <div class="container-bloc-dashboard-head">
            <h5 class="m-0">Modifier le produit</h5>
        </div>
        <div class="p-3 content-form-dashboard">
            {{ include('user_dashboard/product/_form.html.twig', {'button_label': 'Enregistrer'}) }}

            {{ include('user_dashboard/product/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/user_dashboard/product/index.html.twig
{% extends 'user_dashboard/index.html.twig' %}

{% block content %}
    <div class="container-bloc-dashboard">
        <div class="container-bloc-dashboard-head w-100">
            <h5 class="m-0">Liste des produits</h5>
        </div>
        <div class="table-content py-3">
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Product_title</th>
                    <th>Product_price</th>
                    <th>Product_description</th>
                    <th>Product_created_at</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.id }}</td>
                        <td>{{ product.productTitle }}</td>
                        <td>{{ product.productPrice }}</td>
                        <td>{{ product.productDescription }}</td>
                        <td>{{ product.productCreatedAt ? product.productCreatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td class="d-flex align-items-center">
                            <a href="{{ path('app_product_show', {'id': product.id}) }}" target=”_blank”><button class="action-button">Afficher</button></a>
                            <a href="{{ path('app_user_dashboard_product_edit', {'id': product.id}) }}"><button class="action-button">Éditer</button></a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/user_dashboard/product/new.html.twig
{% extends 'user_dashboard/index.html.twig' %}

{% block content %}
    <div class="container-bloc-dashboard w-50">
        <div class="container-bloc-dashboard-head">
            <h5 class="m-0">Nouveau produit</h5>
        </div>
        <div class="p-3 content-form-dashboard">
            {{ include('user_dashboard/product/_form.html.twig') }}
        </div>
    </div>
{% endblock %}